name: Readme checker


on:
  pull_request:
    branches:
      - main

jobs:
  lint_code:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to run the Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: "main"             
          VALIDATE_ALL_CODEBASE: "true"      
          VALIDATE_PYTHON: "true"            
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
                     #
