name: Readme checker

on:
  pull_request:
    branches:
      - main

jobs:
  test_pull:
    runs-on: ubuntu-latest
    steps:
      - name: lint for check the code 
        uses: actions/checkout@v2
        uses: github/super-linter@v4
        
       env:
          
          VALIDATE_ALL_CODEBASE: "true"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON = "true"
          DEFAULT_BRANCH: "main"