name: Readme checker

# Trigger the workflow for pull requests targeting main, successful, and failed branches.
on:
  pull_request:
    branches:
      - main
    

jobs:
  lint_code:
    runs-on: ubuntu-latest
    steps:
      # Step to checkout the code from the pull request
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to run the Super-Linter
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: "main"             # The default branch for comparison
          VALIDATE_ALL_CODEBASE: "true"      # Ensures all files are linted
          VALIDATE_PYTHON: "true"            # Validate Python files in the repository
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token to allow linter access to the repository
                     # The default branch for comparison

