name: Readme checker

on:
  pull_request:
    branches:
      - main

jobs:
  test_pull:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint for check the code 
       uses: github/super-linter@v4
        
       env:
          
          VALIDATE_ALL_CODEBASE: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON = true
          DEFAULT_BRANCH: main